// the optional types are not assignable to trainer cards
export interface Cards {
  id: string;
  name: string;
  supertype: string;
  subtypes: string[];
  hp?: string;
  types?: string[];
  evolvesFrom?: string;
  abilities?: Ability[];
  attacks?: Attack[];
  weaknesses?: Qualities[];
  retreatCost?: string[];
  convertedRetreatCost?: number;
  resistances?: Qualities[];
  set: Set;
  number: string;
  artist: string;
  rarity: string;
  nationalPokedexNumbers: number[];
  legalities: Legalities;
  images: CardsImages;
  tcgplayer?: Tcgplayer;
  cardmarket?: Cardmarket;
}

export interface Ability {
  name: string;
  text: string;
  type: string;
}

export interface Attack {
  name: string;
  cost: string[];
  convertedEnergyCost: number;
  damage: string;
  text: string;
}

export interface Cardmarket {
  url: string;
  updatedAt: string;
  prices: Tiers[];
}

export interface CardsImages {
  small: string;
  large: string;
}

export interface Legalities {
  unlimited: string;
}

export interface Qualities {
  type: string;
  value: string;
}

export interface Set {
  id: string;
  name: string;
  series: string;
  printedTotal: number;
  total: number;
  legalities: Legalities;
  ptcgoCode: string;
  releaseDate: string;
  updatedAt: string;
  images: SetImages;
}

export interface SetImages {
  symbol: string;
  logo: string;
}

export interface Tcgplayer {
  url?: string;
  updatedAt?: string;
  prices?: Prices;
}

export interface Holofoil {
  low?: number;
  mid?: number;
  high?: number;
  market?: number;
}
export interface Prices {
  normal?: Tiers[]
  reverseHolofoil?: Tiers[]
}
// Generated by https://quicktype.io

export interface Tiers {
  low?: number;
  mid?: number;
  high?: number;
  market?: number;
  directLow?: number;
  averageSellPrice?: number;
  lowPrice?: number;
  trendPrice?: number;
  reverseHoloSell?: number;
  reverseHoloLow?: number;
  reverseHoloTrend?: number;
  lowPriceExPlus?: number;
  avg1?: number;
  avg7?: number;
  avg30?: number;
  reverseHoloAvg1?: number;
  reverseHoloAvg7?: number;
  reverseHoloAvg30?: number;
}
