export const thunderBasicDeck:string = `****** Pokémon Trading Card Game Deck List ******

##Pokémon - 26

* 4 Eevee AOR 63
* 2 Kangaskhan FCO 75
* 4 Rattata BKP 87
* 3 Spearow ROS 65
* 2 Fearow ROS 66
* 3 Magnemite BKT 52
* 4 Pikachu BKT 48
* 4 Voltorb ROS 21

##Trainer Cards - 15

* 1 Sky Field ROS 89
* 2 Tierno BKP 112
* 2 Shauna FCO 111
* 1 Pokémon Fan Club FCO 107
* 1 Winona ROS 96
* 2 Lucky Helmet AOR 77
* 2 Ultra Ball FCO 113
* 2 Acro Bike PRC 122
* 1 Potion BKP 106
* 1 Revive ROS 88

##Energy - 19

* 19 Lightning Energy XYEnergy 6

Total Cards - 60

****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******`;



